class CompletionException(RuntimeError):
    """Class of exceptions thrown in Wallet#complete_tx"""
